project:
  type: website #type of project
  output-dir: docs #folder to save files
  
website:
  site-url: https://lanholeto.github.io/portfolio/
  description: "Researcher and educator with cell and molecular expertise "
  favicon: img/icons8-human.svg
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
    - href: index.qmd
      text: <i class="bi bi-house-door-fill"></i>
      
    - href: about/about.qmd
      text: "About"
      
    - href: research/research.qmd
      text: "Research"
          
    - href: publications/publications.qmd
      text: "Publications"
          
    - href: cv/cv.qmd
      text: "CV"

    - href: contact/contact.qmd
      text: "Contact"
      
    tools:
    - icon: envelope
      href: mailto:luis.anholeto@cadiau.ca
    - icon: github
      href: https://github.com/lanholeto
    - icon: twitter-x
      href: https://twitter.com/lanholeto
    - icon: linkedin
      href: https://www.linkedin.com/in/lanholeto
    - icon: mortarboard-fill
      href: https://scholar.google.com/citations?user=dlkP2zUAAAAJ&hl=en
    - icon: person-circle
      href: https://orcid.org/0000-0001-8712-2630
      
  
  #control footpage 
  page-footer:
    border: false
    background: "#000000"
    left: "© last modified April 28, 2025 - Luís Adriano Anholeto"

#control format for all pages 
format:
  html:
    theme: [lux, lux.scss]
    toc: true
    toc-floating: true